# Generated by Django 5.2.9 on 2025-12-07 17:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=255, unique_for_date='published_at', verbose_name='URL-адреса')),
                ('content', models.TextField(verbose_name='Контент')),
                ('excerpt', models.TextField(blank=True, max_length=500, verbose_name='Короткий опис')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публікації')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубліковано')),
                ('status', models.CharField(choices=[('draft', 'Чернетка'), ('published', 'Опубліковано')], default='draft', max_length=10, verbose_name='Статус')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Стаття',
                'verbose_name_plural': 'Статті',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100, verbose_name="Ім'я автора")),
                ('author_email', models.EmailField(max_length=254, verbose_name='Email автора')),
                ('content', models.TextField(verbose_name='Текст коментаря')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
                ('is_approved', models.BooleanField(default=True, verbose_name='Схвалено')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='posts.article', verbose_name='Стаття')),
            ],
            options={
                'verbose_name': 'Коментар',
                'verbose_name_plural': 'Коментарі',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['-published_at'], name='posts_artic_publish_750238_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['slug'], name='posts_artic_slug_b76bbc_idx'),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['created_at'], name='posts_feedb_created_9118e3_idx'),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['is_approved'], name='posts_feedb_is_appr_cd8318_idx'),
        ),
    ]
