version: '3.8'

services:
  
  python-app:
    build:
      context: .
      dockerfile: Dockerfile
    
    image: my-python-app:latest
    
    container_name: python-app-container
    
    ports:
      - "8000:8000"
    
    volumes:
      - ./src:/app/src
    
    restart: unless-stopped
    
    networks:
      - app-network
  
  
  redis:
    image: redis:7-alpine
    
    container_name: redis-container
    
    ports:
      - "6379:6379"
    
    restart: unless-stopped
    
    networks:
      - app-network

networks:
  app-network:
    driver: bridge